os:
- linux
services:
- docker
language: java
node_js:
- 4.5.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
env:
  matrix:
  - NODE_VERSION=4.5.0
  global:
  - secure: L9c/3p5dK/W04L0ZRJArocudsRV6f0BL/EduUw6cVSv0wnuEN5bgWphyrDJ62i57ak8JWrx8NvlMAypb37/tGm5YLmRx8gn9+hrHY9xrhwTQlHO84dVwAWuuwWCKGMcxY+dPJbnumaBtjekVxsw6OFSJ+4LlI2MyAJ1Tvca/5uKXlraXcrkaUEnuJqLVMHBb0CcE7IFOo6PQ+YnBc5FXykprNFpqryXeRE/5DVDmd8c7rx/r9Z96ulQbAYFelCAkK5vLfCaHyf17U5FygZObGOvF/f1kOJ0BNy0t/Vs1z5r8pVIcByj6qgZoqPduIjhjgMtp6SnXM/Fw3e1wJ9MBzETni5BlAQcDEyMbSHEUbf9sZOemOq9i6hUWAUCK6tnGiMsvl34iptv4CGE9uDv9Qn/bsLmdLtwxKEE2E0bcSsrcB2Ve6ntpgfWExGYoqve6z1WFgnkHp+/LbRCAYQsJzJx+qZB1GGapXAz47j9gVuPWYk7ri8wq8CBGB8OLRky99/pbq986BqHCivssBPcJdFbGrSxAL7rS49txLN4ErHvw+tJQldUp3jBzgx9yzrjUfWUIuIGU+rntrvOQEQY2TQcXzOBw4GC8Sm8vMbyzE/KZISXLC2H5sq0eTkxrjbUGLgfNEtQTJql3v6ZOKm8tmvSzeev5UmU5gRMkreMrcRg=
  - secure: ssxhcqo40amZGlF/Vt7I01QMEFbz45CTeuZJVZNgpR4lLmb6VEiosHe2RjSPE2ZypWPuedZRFXdJpyTRFyIGqYveeB776uvkBsA6XS1zJxzwgSecvo5C7S48yFQhKDj3TyWpJSgAtngLafDlLcDKndk7nGCKgJEqine47uCDFLaVsE7/v0uhe3SAFchazGSTjTyURki/3rR508HMZUbe3MKYGGZUZeG4e6GF19haqGfSZUqrXP67K8Oo4vcOVIQSfpS/8xEy39tdmD3u48QPyraVU2Yr/gm56Ru62Zrvl0m8RtA1Z70srufMjTwrG6z95vU8PiM2qmLc5Yb7qR2rmmwri98vMKnAByakjDV0p5n6JdDHL5HszZRHhGa4FK8Q7LElIMYZY9I+re+UW/ZR3xsNZRd06kbnYvnds584JiGwPejXwphx+cuGgDSe2LBF2QHJwfoM2OC3LzcNyQR0hx9MYeT+Ecoq+L8aNxsYDgNmmZ/H2guTkmiVQsrKFUalaL5YtyuMKGUMpn8v4MJdwQP1rOfFidV6dfwh7OJamEioN8q+fb/a5/CjFE/T6Nzr9e+vuojpS+sYdabYSn626lza3Cs8BPq6mIQ5h+c3QapM7bBi7/ptjkb+UALr7XsJ5rGm9fjhQnJ2heMehP/QJDtRWvWeL5E7rjY4CYs8dK8=
before_install:
- nvm install $NODE_VERSION
- npm install -g npm
- npm install -g bower gulp-cli
- node -v
- npm -v
- bower -v
- gulp -v
- java -version
install: npm install
script:
- ./mvnw clean
- ./mvnw test
- gulp test
- mkdir -p target/reports/e2e/screenshots/
- docker-compose -f src/main/docker/mysql.yml up
- sleep 20s
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- mvn spring-boot:run &
- bootPid=$!
- sleep 60s
- gulp itest
- ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
